### ISSUE TITLE
IMM detector and get_files_list

### ISSUE THREAD

**Issue by dylanmcreynolds** [bluesky/area-detector-handlers#9]
While trying to export data 8-ID-I, we found that the handler for the IMM detector was missing a get_files_list() method. 

We played around in the time we had, but were unable to test our proposed implementation. @gwbischof  or @prjemian can you please add the implementation you were testing?

**Comment by danielballan** [comment]
@prjemian shared the implementation via Slack. I posted it in #10 and added a test.
